<a href="https://colab.research.google.com/github/Mehul27/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

In [11]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
# Get tensor back as python int
scalar.item()

7

In [14]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [35]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [45]:
TENSOR2 = torch.tensor([[[[1, 2],[3, 4]], [[5, 6], [7, 8]]], [[[2, 1],[4, 3]], [[6, 5], [8, 7]]]])
TENSOR2

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]],


        [[[2, 1],
          [4, 3]],

         [[6, 5],
          [8, 7]]]])

In [46]:
TENSOR2.ndim

4

In [47]:
TENSOR2.shape

torch.Size([2, 2, 2, 2])

In [48]:
TENSOR2[0]

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [49]:
TENSOR2[1]

tensor([[[2, 1],
         [4, 3]],

        [[6, 5],
         [8, 7]]])