<a href="https://colab.research.google.com/github/Mehul27/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

In [11]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
# Get tensor back as python int
scalar.item()

7

In [14]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [35]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [45]:
TENSOR2 = torch.tensor([[[[1, 2],[3, 4]], [[5, 6], [7, 8]]], [[[2, 1],[4, 3]], [[6, 5], [8, 7]]]])
TENSOR2

tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]],


        [[[2, 1],
          [4, 3]],

         [[6, 5],
          [8, 7]]]])

In [46]:
TENSOR2.ndim

4

In [47]:
TENSOR2.shape

torch.Size([2, 2, 2, 2])

In [48]:
TENSOR2[0]

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [49]:
TENSOR2[1]

tensor([[[2, 1],
         [4, 3]],

        [[6, 5],
         [8, 7]]])

### Random tensors

Why random tensors?

Important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [58]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(2, 5, 4)
random_tensor

tensor([[[0.1980, 0.1922, 0.5915, 0.8076],
         [0.9269, 0.1661, 0.1063, 0.3365],
         [0.1560, 0.0078, 0.9920, 0.3123],
         [0.6334, 0.2893, 0.2715, 0.4677],
         [0.1700, 0.5680, 0.7584, 0.5710]],

        [[0.7506, 0.8735, 0.6591, 0.7733],
         [0.9114, 0.0765, 0.1689, 0.7292],
         [0.0273, 0.7508, 0.7887, 0.9984],
         [0.4950, 0.4176, 0.0707, 0.3357],
         [0.1120, 0.3788, 0.4062, 0.8487]]])

In [59]:
random_tensor.ndim

3

In [60]:
random_tensor.shape

torch.Size([2, 5, 4])

In [63]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [64]:
# Create a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
# Create a tensor of all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
ones.dtype

torch.float32

In [68]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [73]:
# Use torch.range
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:**  Tensor datatypes is one of the 3 big errors you will run into with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [82]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (eg. float32, float64)
                               device=None, # Which device is this tensor on (eg: cpu, cuda/gpu)
                               requires_grad=False) # Whether or not to track gradients for this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [83]:
float_32_tensor.dtype

torch.float32

In [85]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [86]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [91]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [92]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [94]:
# Create a tensor
some_tensor = torch.rand([3, 4])
some_tensor

tensor([[0.5572, 0.7163, 0.4098, 0.9641],
        [0.6308, 0.2752, 0.1947, 0.6385],
        [0.2760, 0.7346, 0.2605, 0.0666]])

In [95]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device of some_tensor: {some_tensor.device}")

tensor([[0.5572, 0.7163, 0.4098, 0.9641],
        [0.6308, 0.2752, 0.1947, 0.6385],
        [0.2760, 0.7346, 0.2605, 0.0666]])
Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [96]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [98]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [99]:
tensor

tensor([1, 2, 3])

In [101]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [103]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([11, 12, 13])

In [104]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (Dot Product)

In [109]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [111]:
sample_tensor1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
sample_tensor1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [112]:
sample_tensor2 = torch.tensor([[7, 8],
                                [9, 10],
                                 [11, 12]])
sample_tensor2

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [115]:
# Matrix Multiplication (Dot Product)
sample_tensor1.matmul(sample_tensor2)

tensor([[ 58,  64],
        [139, 154]])

In [116]:
torch.matmul(sample_tensor1, sample_tensor2)

tensor([[ 58,  64],
        [139, 154]])